### ISSUE TITLE
您好，能否做成订阅地址？

### ISSUE THREAD

**Issue by choushui007** [dxxzst/Free-SS-SSR#10]
如题，我是路由器openwrt翻墙的，能够给个订阅地址？

**Comment by kanye0405** [comment]
根据下面url地址看到group是 [WWW.SSRTOOL.COM](https://WWW.SSRTOOL.COM)
然后登陆上面的网站（需翻墙）可以找到订阅地址，订阅后和readme.md文件里给的一样

https://raw.githubusercontent.com/AmazingDM/sub/master/ssrshare.com
我直接把地址贴过开好了。
如果还有疑问，建议直接上[WWW.SSRTOOL.COM](https://WWW.SSRTOOL.COM)看一下，里面有很多工具。

**Comment by Elliott-cui** [comment]
怎么制作订阅地址呢  
我用SSR小工具上把给出的这个网页上的信息转换成JSON 但是出来的代码就一行 还没有内容

**Comment by Elliott-cui** [comment]
我理解错了    我找到小工具网站上的订阅地址了    非常感谢

**Comment by choushui007** [comment]
能否共享一下


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Elliott-cui <notifications@github.com>
发送时间: 2019年5月15日 09:26
收件人: dxxzst/Free-SS-SSR <Free-SS-SSR@noreply.github.com>
抄送: choushui007 <878779616@qq.com>, Author <author@noreply.github.com>
主题: 回复：[dxxzst/Free-SS-SSR] 您好，能否做成订阅地址？ (#10)




我理解错了    我找到小工具网站上的订阅地址了    非常感谢

**Comment by Elliott-cui** [comment]
> 能否共享一下 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Elliott-cui <notifications@github.com> 发送时间: 2019年5月15日 09:26 收件人: dxxzst/Free-SS-SSR <Free-SS-SSR@noreply.github.com> 抄送: choushui007 <878779616@qq.com>, Author <author@noreply.github.com> 主题: 回复：[dxxzst/Free-SS-SSR] 您好，能否做成订阅地址？ (#10) 我理解错了 我找到小工具网站上的订阅地址了 非常感谢 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

上面那个就是

**Comment by GetViewer** [comment]
在哪，还是没找到。。上面的也不能用
