### ISSUE TITLE
您好，我用的不太熟，请问协议和混淆应该怎么选呢？

### ISSUE THREAD

**Issue by luftpan** [dxxzst/Free-SS-SSR#14]

**Comment by mx342** [comment]
你应该文up主
------------------ 原始邮件 ------------------
发件人: "luftpan"<notifications@github.com>;
发送时间: 2019年5月19日(星期天) 晚上7:59
收件人: "dxxzst/Free-SS-SSR"<Free-SS-SSR@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [dxxzst/Free-SS-SSR] 您好，我用的不太熟，请问协议和混淆应该怎么选呢？ (#14)

**Comment by dxxzst** [comment]
@luftpan 如果用SSR，请用第二个表中的SSR链接，直接导入就行了。
具体使用可以参考 [ShadowsocksR-SSR 在Windows上的使用及设置方法](https://www.youneed.win/shadowsocksr-ssr-%E5%9C%A8windows%E4%B8%8A%E7%9A%84%E4%BD%BF%E7%94%A8%E5%8F%8A%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95.html)
