### ISSUE TITLE
大神教教我怎么用。。

### ISSUE THREAD

**Issue by kaifengace** [dxxzst/Free-SS-SSR#17]

**Comment by dxxzst** [comment]
@kaifengace 这个还用教？很容易就查到吧

**Comment by dxxzst** [comment]
@kaifengace 可以参考[ShadowsocksR-SSR 在Windows上的使用及设置方法](https://www.youneed.win/shadowsocksr-ssr-%E5%9C%A8windows%E4%B8%8A%E7%9A%84%E4%BD%BF%E7%94%A8%E5%8F%8A%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95.html)
[Shadowsocks 在Windows上的使用及设置方法](https://www.youneed.win/shadowsocks-%E5%9C%A8windows%E4%B8%8A%E7%9A%84%E4%BD%BF%E7%94%A8%E5%8F%8A%E8%AE%BE%E7%BD%AE%E6%96%B9%E6%B3%95.html)

**Comment by ncc0706** [comment]
@kaifengace 是妹子就教你
