### ISSUE TITLE
作者你为何这么牛皮

### ISSUE THREAD

**Issue by ghost** [dxxzst/Free-SS-SSR#2]
俗话说知识就是力量，信息就是财富，敢问作者可否透露一点信息来源

**Comment by dxxzst** [comment]
@GitRainy 爬虫而已

**Comment by 418092834** [comment]
文科生路过。正在学习编程，这是一个神奇的世界

**Comment by The3Third** [comment]
我们是站在巨人的肩膀上 正因为一些人的无私奉献 才能在着Cave中获得片刻的free 
人类正因大佬们的分享 众小白们才能沿着他们开拓的路途上继续前行

**Comment by hoochanlon** [comment]
爬虫搬运free-ss.site和tool的GitHub版
