### ISSUE TITLE
辛苦了，就是最近墙的好厉害，都是不能用了

### ISSUE THREAD

**Issue by ixiaoqing** [dxxzst/Free-SS-SSR#26]
最近墙的好厉害，我也是配置一个被封一个，我都怀疑是ssr手机端或电脑端被识别了，但被墙了，也不好找最新的ssr客户端，有没有一些技术上的指导给提一下呢？

**Comment by 774471872** [comment]
> 最近墙的好厉害，我也是配置一个被封一个，我都怀疑是ssr手机端或电脑端被识别了，但被墙了，也不好找最新的ssr客户端，有没有一些技术上的指导给提一下呢？

别找了，6月4日快到了，今年是30周年，怎么搞都不行

**Comment by DaLiangLee** [comment]
服务器被封了好几个了。。ε=(´ο｀*)))唉

**Comment by rorschach214** [comment]
我的vultr全挂了 倒是赛风还可以用

**Comment by qqlovekerry** [comment]
ss是不是以后就没法用了啊，自己的ip全被禁了，今天换了好几个这里的IP也连不上了，各位大神有没有别的不容易被qiang的办法指导下呢？

**Comment by rorschach214** [comment]
找到新的了，目前还挺快的 一个月不到20 ，搬瓦工自己搞得ss，https://justmysocks.net/members/aff.php?aff=1739 ，参数是推广码，介意的话可以删除

**Comment by dxxzst** [comment]
@rorschach214 不要推广哦
