### ISSUE TITLE
IP可以ping通但是ss翻不了qiang?

### ISSUE THREAD

**Issue by qqlovekerry** [dxxzst/Free-SS-SSR#27]
感谢作者大大的分享！不过今天我遇到的问题是IP是可以ping通的，但是ss无法fanqiang，请问下大家都是这样吗？ss以后要没用了？求各位大大指路

**Comment by micenote** [comment]
非常时期。基本上全挂了！

**Comment by qqlovekerry** [comment]
> 非常时期。基本上全挂了！

前几天的都是IP被禁了，今天我这里试的IP可以ping通但是还是不能fanqiang，不会ss要挂吧，好悲剧，这几天买了好几个VPS，都没用了

**Comment by dxxzst** [comment]
最近比较严，过阵子就好了

**Comment by qqlovekerry** [comment]
> 最近比较严，过阵子就好了

希望如此吧，没用过ssr和v2，不知道其他方法还有啥能用的
