### ISSUE TITLE
URL 用不了

### ISSUE THREAD

**Issue by p-z-l** [dxxzst/Free-SS-SSR#3]
URL 无法通过 ShadowsocksX 导入节点。
我试着用过其他SSR的URL都是可用的

**Comment by dxxzst** [comment]
@peterzililuo 用SSR https://github.com/CGDF-Github/SSRR-Windows

**Comment by p-z-l** [comment]
macOS 咋办

**Comment by dxxzst** [comment]
@peterzililuo 可以用mac版https://github.com/ShadowsocksR-Live/ssrMac
