### ISSUE TITLE
www.flywind.ml域名登录不上，显示offline

### ISSUE THREAD

**Issue by goSpectre** [dxxzst/Free-SS-SSR#38]

**Comment by goSpectre** [comment]
help me

**Comment by goSpectre** [comment]
I need to link to www.coursera.org to learn python data analysis

**Comment by dxxzst** [comment]
已恢复

**Comment by goSpectre** [comment]
感谢！
  

 

 ------------------ 原始邮件 ------------------
  发件人: "DXXZST"<notifications@github.com>;
 发送时间: 2019年8月22日(星期四) 下午2:33
 收件人: "dxxzst/Free-SS-SSR"<Free-SS-SSR@noreply.github.com>;
 抄送: "下雨不等伞丶"<852465568@qq.com>;"Author"<author@noreply.github.com>;
 主题: Re: [dxxzst/Free-SS-SSR] www.flywind.ml域名登录不上，显示offline (#38)

 

 
已恢复
