### ISSUE TITLE
https://www.flywind.ml/ 建立数据库连接时出错

### ISSUE THREAD

**Issue by w4ctech** [dxxzst/Free-SS-SSR#39]
![https://www.flywind.ml 建立数据库连接时出错](https://user-images.githubusercontent.com/33955669/63479369-a6a35e00-c4c0-11e9-8680-5895455e3a86.png)
url : https://www.flywind.ml/ 
响应：建立数据库连接时出错
时间 2019/8/22 9 : 38

**Comment by dxxzst** [comment]
已恢复
