### ISSUE TITLE
兄dei 你为什么不害怕被抓起来？

### ISSUE THREAD

**Issue by chenqq2016** [dxxzst/Free-SS-SSR#41]
兄dei 你为什么不害怕被抓起来？

**Comment by LeungYu** [comment]
这位老哥估计肉身在外面

**Comment by LeungYu** [comment]
我有个师兄在NUS留学的时候搞这个赚钱，现在被内地通缉了，直接申请庇护，特殊渠道入了坡籍

**Comment by q3v5** [comment]
> 我有个师兄在NUS留学的时候搞这个赚钱，现在被内地通缉了，直接申请庇护，特殊渠道入了坡籍

这是高手
