### ISSUE TITLE
能弄个新域名吗

### ISSUE THREAD

**Issue by wjr050430** [dxxzst/Free-SS-SSR#45]
这边没有hosts修改权限，希望博主尽快更新新域名

**Comment by dxxzst** [comment]
@wjr050430 可以使用火狐浏览器，并进行一些设置，参考：https://www.cccitu.com/3913.html

**Comment by wjr050430** [comment]
我是手机，没法root，还有别的方法吗？ 在2019年09月28日 19:36，DXXZST 写道： Closed #45. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
