### ISSUE TITLE
长期稳定高速 ssr://MTQ5LjI4LjI0MS4xMzE6MjE4NDI6b3JpZ2luOmNoYWNoYTIwLWlldGYtcG9seTEzMDU6cGxhaW46VnpJd01UbFQvP3JlbWFya3M9NUx1WTZMUzU2YXVZNllDZjU2aXo1YTZhVVZFeU1UYzFPVFEwTVRNdyZwcm90b3BhcmFtPSZvYmZzcGFyYW09

### ISSUE THREAD

**Issue by ghost** [dxxzst/Free-SS-SSR#50]
ssr://MTQ5LjI4LjI0MS4xMzE6MjE4NDI6b3JpZ2luOmNoYWNoYTIwLWlldGYtcG9seTEzMDU6cGxhaW46VnpJd01UbFQvP3JlbWFya3M9NUx1WTZMUzU2YXVZNllDZjU2aXo1YTZhVVZFeU1UYzFPVFEwTVRNdyZwcm90b3BhcmFtPSZvYmZzcGFyYW09

**Comment by p19971018** [comment]
这玩意怎么用？
