### ISSUE TITLE
火狐浏览器无法正常浏览

### ISSUE THREAD

**Issue by r322020** [dxxzst/Free-SS-SSR#54]
系统为Debian10
全部默认设置，显示"

系统检测到您正在使用广告拦截插件，请将本站添加至白名单或关闭广告拦截插件，然后点击这里继续访问本站。"

**Comment by dxxzst** [comment]
你好，可以将火狐的内容拦截改为标准，并对本站添加例外。
可以参考 https://jingyan.baidu.com/article/72ee561a23f7a5e16138dfa8.html

r322020 <notifications@github.com> 于2020年1月6日周一 下午5:37写道：

**Comment by r322020** [comment]
内容拦截已经是 标准

**Comment by SKERING** [comment]
@已经修复
